name: Format (prettier)

on: pull_request

jobs:
    prettier:
        name: Prettier
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.head_ref }}
        - name: Use Node.js v10.x
          uses: actions/setup-node@v1
          with:
            version: '10.x'

        - name: Install yarn, run prettier
          run: |
            npm install -g yarn
            yarn install
            yarn run prettier --write 'src/**/*.{tsx,js}'

        - uses: stefanzweifel/git-auto-commit-action@v2.5.0
          with:
            commit_message: Apply php-cs-fixer changes
            branch: ${{ github.head_ref }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
